language: go

dist: xenial

go:
- 1.16

os:
  - linux

addons:
  sonarcloud:
    organization: "pp-groupe-6"
    token: ${SONAR_TOKEN}
    
script:
  - go test -v ./account_microservice
  - go test -v ./transaction_microservice
  - sonar-scanner
