language: go

dist: xenial

go:
- 1.16

before_install:
  - ./travis/before_install.bash

os:
  - linux
  
env:
  global:
    - GO111MODULE=on
    - PGX_TEST_DATABASE=postgres://pgx_md5:secret@127.0.0.1/pgx_test
    - PGX_TEST_UNIX_SOCKET_CONN_STRING="host=/var/run/postgresql database=pgx_test"
    - PGX_TEST_TCP_CONN_STRING=postgres://pgx_md5:secret@127.0.0.1/pgx_test
    - PGX_TEST_TLS_CONN_STRING=postgres://pgx_md5:secret@127.0.0.1/pgx_test?sslmode=require
    - PGX_TEST_MD5_PASSWORD_CONN_STRING=postgres://pgx_md5:secret@127.0.0.1/pgx_test
    - PGX_TEST_PLAIN_PASSWORD_CONN_STRING=postgres://pgx_pw:secret@127.0.0.1/pgx_test
  matrix:
    - CRATEVERSION=2.1 PGX_TEST_CRATEDB_CONN_STRING="host=127.0.0.1 port=6543 user=pgx database=pgx_test"
    - PGVERSION=11 PGX_TEST_REPLICATION_CONN_STRING="host=127.0.0.1 port=6543 user=pgx_replication password=secret database=pgx_test"
    - PGVERSION=10 PGX_TEST_REPLICATION_CONN_STRING="host=127.0.0.1 port=6543 user=pgx_replication password=secret database=pgx_test"
    - PGVERSION=9.6 PGX_TEST_REPLICATION_CONN_STRING="host=127.0.0.1 port=6543 user=pgx_replication password=secret database=pgx_test"
    - PGVERSION=9.5
    - PGVERSION=9.4

addons:
  sonarcloud:
    organization: "pp-groupe-6"
    token: ${SONAR_TOKEN}
    
before_script:
  - ./travis/before_script.bash

script:
  - go test -v ./account_microservice
  - go test -v ./transaction_microservice
  - sonar-scanner
